export enum ERole {
  SYSTEM_SUPER_ADMIN = 'SYSTEM_SUPER_ADMIN',
  SYSTEM_MANAGER = 'SYSTEM_MANAGER',
  TEMPLE_SUPER_ADMIN = 'TEMPLE_SUPER_ADMIN',
  TEMPLE_MANAGER = 'TEMPLE_MANAGER',
  FAMILY_ADMIN = 'FAMILY_ADMIN',
  FAMILY_MEMBER = 'FAMILY_MEMBER',
  PUBLIC_USER = 'PUBLIC_USER',
  GUEST = 'GUEST',
}

export enum EStoreName {
  AUTH = 'auth',
  COMMON = 'common',
  PAGINATION = 'pagination',
}
